version: "3"
services:
  database:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: mypassword
      POSTGRES_USER: postgres_user
      POSTGRES_DB: open_pdf
    volumes:
      - pg_data:/var/lib/postgresql/data
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    links:
      - database
  open_chat_pdf:
    env_file:
      - server/.env
    build: .
    ports:
      - 8000:8000
    depends_on:
      - database
    links:
      - database
    volumes:
      - ./uploads:/server/uploads
volumes:
  pg_data:
