version: "3"
services:
  open_chat_pdf:
    env_file:
      - .env
    build: .
    ports:
      - 8000:8000
    depends_on:
      - database
    links:
      - "database:database"
  database:
    image: postgres
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mypassword
    volumes:
      - local_pgdata:/var/lib/postgresql/data
