version: "3"
services:
  database:
    image: postgres
    container_name: postgres_db
    hostname: postgres_db
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: mypassword
      POSTGRES_USER: david
      POSTGRES_DB: open_pdf
    volumes:
      - local_pgdata:/var/lib/postgresql/data
  open_chat_pdf:
    env_file:
      - server/.env
    build: .
    ports:
      - 8000:8000
    depends_on:
      - database
    links:
      - "database:database"
volumes:
  local_pgdata: